client_id = "0f537664f7a9cdfda5af723a97b7c689"
name = "Pricingspy"
application_url = "https://pricingspy.vercel.app/api/shopify/install"
embedded = false

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = ["customers/data_request", "customers/redact", "shop/redact"]
  uri = "/api/shopify/webhooks/compliance"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/api/shopify/webhooks/app/uninstalled"

[access_scopes]
scopes = "read_products,write_products"
optional_scopes = []
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://pricingspy.vercel.app/api/auth",
  "https://pricingspy.vercel.app/api/shopify/callback"
]
